{
    "plugins": [
        "react"
    ],
    "env":{
        "browser": true,
        "node": true
    },
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "rules": {
        "semi": 2
    },
    "extends": [
        "eslint:recommended",
        "plugin:react/recommended" 
    ],
    "parser": "babel-eslint"
}